-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Henkilo CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Henkiloidenryhmat CASCADE;
DROP TABLE IF EXISTS Kayttajat CASCADE;

